import React from 'react';
import Link from 'next/link';
import BrandLogo from '../BrandLogo';

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#030712] text-slate-300 font-sans selection:bg-[#635A80]/30">
      {/* Simple Header */}
      <nav className="w-full p-6 border-b border-white/[0.06] flex items-center justify-between sticky top-0 bg-[#030712]/80 backdrop-blur-xl z-50">
        <Link href="/">
          <BrandLogo />
        </Link>
        <Link href="/" className="text-sm font-bold text-slate-400 hover:text-white transition-colors">
          Back to Home
        </Link>
      </nav>

      {/* Hero Section */}
      <section className="relative w-full py-24 px-6 flex flex-col items-center justify-center border-b border-white/[0.06] overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-[#635A80]/5 blur-[120px] rounded-full pointer-events-none" />
        <div className="relative z-10 text-center max-w-3xl mx-auto">
          <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tighter mb-6">
            Privacy Policy
          </h1>
          <p className="text-lg text-slate-500 font-medium">
            Frosty Platform Documentation & Policies
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="w-full py-24 px-6">
        <div className="max-w-3xl mx-auto text-base text-slate-300 leading-relaxed">
          <p className="mb-6">At Frosty (Frostrek LLP), your privacy is our priority. We are committed to protecting your personal data and ensuring transparency in how we collect, use, and process your information when you interact with our autonomous AI agents and platform.</p>
          <h2 className="text-2xl font-bold text-white mb-4 mt-12">1. Data Collection</h2>
          <p className="mb-6">We collect information you provide directly to us when using the Frosty platform, including account details, connected platform credentials (WhatsApp, Slack, etc.), and the conversation logs generated by our AI agents to improve accuracy and context.</p>
          <h2 className="text-2xl font-bold text-white mb-4 mt-12">2. How We Use Data</h2>
          <p className="mb-6">Your data is used to power your specific AI agents. We do not train shared frontier models on your proprietary business data without explicit consent. Logs are strictly isolated per tenant environment.</p>
          <h2 className="text-2xl font-bold text-white mb-4 mt-12">3. Data Security</h2>
          <p className="mb-6">All data in transit and at rest is encrypted using industry-standard protocols. Our infrastructure relies on robust cloud providers with SOC2 compliance.</p>
        </div>
      </section>
      
      {/* Simple Footer */}
      <footer className="w-full py-12 border-t border-white/[0.06] text-center text-sm text-slate-600 font-medium">
        © 2021 Frostrek LLP. All rights reserved.
      </footer>
    </main>
  );
}
